# permissions for end users to view registrysecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registrysecret-viewer-role
rules:
- apiGroups:
  - apps.jaxwood.com
  resources:
  - registrysecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.jaxwood.com
  resources:
  - registrysecrets/status
  verbs:
  - get
