# permissions for end users to edit registrysecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registrysecret-editor-role
rules:
- apiGroups:
  - apps.jaxwood.com
  resources:
  - registrysecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.jaxwood.com
  resources:
  - registrysecrets/status
  verbs:
  - get
