apiVersion: apps.jaxwood.com/v1
kind: RegistrySecret
metadata:
  name: image-pull-secret
  namespace: registry-operator-system
spec:
  imagePullSecretName: "regcred-dev"
  imagePullSecretKey: ".dockerconfigjson"
